#!/bin/bash
#!/bin/bash
source /home/hpc/bisheng4.2_setenv.sh
source /home/hpc/mpi/hmpi25.0.0_setenv.sh
source /home/hpc/hpchq/openfoam/OpenFOAM-v2212/etc/bashrc WM_COMPILER=Clang WM_PRECISION_OPTION=SPDP

mpirun --allow-run-as-root -np 128 renumberMesh -overwrite -parallel

time -p mpirun --allow-run-as-root -x UCX_LOG_LEVEL=0 -x VERBS_LOG_LEVEL=0 -x UCX_NET_DEVICES=hns_1:1 -x UCX_TLS=sm\
	 -np 512 --cpu-set 4-35,42-73,80-111,118-149,156-187,194-225,232-263,270-301,308-339,346-377,384-415,422-453,460-491,498-529,536-567,574-605 \
	--bind-to cpulist:ordered pisoFoam -parallel 2>&1 | tee openfoam-2025-06-07-SPDP.log
